name: Update README
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: actions/checkout@v4

      - name: Checkout github-contrib-stats
        uses: actions/checkout@v4
        with:
          repository: j178/github-contrib-stats
          ref: b6efdd483ecfa2927d6e2204fe389929fa61d50b
          path: .github-contrib-stats

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: .github-contrib-stats

      - name: Build github-contrib-stats
        run: cargo install --path .github-contrib-stats/cli --locked

      - name: Update stats
        run: github-contrib-stats -u ${{ github.repository_owner }} --update README.md
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}

      - name: Commit files
        run: |
          if git diff --quiet; then
            echo "nothing new"
            exit 0
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update README"
          git push
